apiVersion: v1
kind: Pod
metadata:
metadata:
  # 'name' è l'identificatore tecnico e univoco del pod all'interno del cluster/container engine.
  # Deve essere unico per ogni pod e viene usato dai comandi di gestione (es: podman, kubectl).
  name: digitaltwin-${POD_NAME}

  labels:
    # 'app' è una label generica che permette di raggruppare tutte le risorse che fanno parte della stessa applicazione.
    app: DigitalTwin

    # 'instance' è una label logica che identifica l'istanza funzionale o il ruolo del pod.
    # Può essere usata per filtrare, monitorare o gestire gruppi di pod che rappresentano, ad esempio, diversi palletizer.
    # A differenza di 'name', può essere duplicata su più pod se necessario.
    instance: ${POD_NAME}
spec:
  restartPolicy: Always

  containers:
    
    - name: mosquitto
      image: docker.io/eclipse-mosquitto:latest
      ports:
        - containerPort: 1883
          hostPort: ${HOST_PORT}.   # Qui imposto una porta per essere raggiungibile dall'esterno
          protocol: TCP
      volumeMounts:
        - name: mosquitto-conf
          mountPath: /mosquitto/config 

    - name: timescaledb
      image: docker.io/timescale/timescaledb:latest-pg15
      ports:
        - protocol: TCP
      command:                     # Imposto qui le variabili di ambiente per via di un problema noto con le immagini postgres (sul quale timescaleDB è basato)
          - /bin/bash
          - -c
          - |
            echo "Avvio TimescaleDB con setup automatico..."
            
            export POSTGRES_HOST_AUTH_METHOD=trust        
            export POSTGRES_DB=mqtt_data
            export POSTGRES_USER=mqtt_user
            export POSTGRES_PASSWORD=mqtt_password
            export POSTGRES_INITDB_ARGS="--auth-host=trust --auth-local=trust"
            
            if [ ! -f /var/lib/postgresql/data/PG_VERSION ]; then
              echo "Database non esistente, inizializzazione automatica..."
            else
              echo "Database esistente trovato, avvio normale"
            fi
            
            echo "Avvio PostgreSQL/TimescaleDB con variabili impostate..."
            exec docker-entrypoint.sh postgres
        
      volumeMounts:
        - name: timescale-data
          mountPath: /var/lib/postgresql/data
        - name: timescale-init
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true

    - name: go-publisher
      image: docker.io/alpine:latest
      workingDir: /app
      command: ["./mqtt_simulation"]
      args: ["${POD_NAME}", "1883"]  # Argomenti Multipli
      environment:
      volumeMounts:
        - name: go-publisher-binary
          mountPath: /app/mqtt_simulation.   # punto di montaggio all'interno del container
          subPath: mqtt_simulation.          # dalla cartella del publisher monta solo il file
          readOnly: true

    - name: go-client
      image: docker.io/alpine:latest
      workingDir: /app
      command: ["./mqtt_to_timescale"]
      args: ["${POD_NAME}"]
      environment:
        - name: MQTT_BROKER
          value: "tcp://localhost:1883"
        - name: DB_HOST
          value: "localhost"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "mqtt_data"
        - name: DB_USER
          value: "mqtt_user"
        - name: DB_PASSWORD
          value: "mqtt_password"
      volumeMounts:
        - name: go-client-binary
          mountPath: /app/mqtt_to_timescale    # punto di montaggio all'interno del container
          subPath: mqtt_to_timescale           # dalla cartella del client monta solo il file
          readOnly: true

    - name: grafana
      image: docker.io/grafana/grafana:latest
      ports:
        - containerPort: 3000
          hostPort: ${GRAFANA_PORT} 
          protocol: TCP
      environment:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"  
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        - name: GF_INSTALL_PLUGINS
          value: "grafana-clock-panel,grafana-simple-json-datasource"
        - name: POD_NAME
          value: "${POD_NAME}" 
      volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
        - name: grafana-config
          mountPath: /etc/grafana/provisioning
          readOnly: true
        - name: grafana-ini
          mountPath: /etc/grafana/grafana.ini   # punto di montaggio all'interno del container
          subPath: grafana.ini                  # da grafana-ini monta solo il file grafana.ini
          readOnly: true

  volumes:                   # I volumi vengono dichiarati separatamente, da notare che non viene dichiarata nessuna rete
    # Configurazione Mosquitto
    - name: mosquitto-conf
      hostPath:
        path: ${PWD}/mosquitto
        type: Directory

    # Binario simulatore MQTT
    - name: go-publisher-binary
      hostPath:
        path: ${PWD}/go_simulation
        type: Directory

    # Binario client Go
    - name: go-client-binary
      hostPath:
        path: ${PWD}/go_to_timescale
        type: Directory

    # Dati persistenti TimescaleDB (creati automaticamente se non esistono)
    - name: timescale-data
      hostPath:
        path: ${PWD}/timescale/data/${POD_NAME}
        type: DirectoryOrCreate

    # Script di inizializzazione TimescaleDB
    - name: timescale-init
      hostPath:
        path: ${PWD}/timescale/init
        type: Directory

    # Dati persistenti Grafana (creati automaticamente se non esistono)
    - name: grafana-data
      hostPath:
        path: ${PWD}/grafana/data/${POD_NAME}
        type: DirectoryOrCreate

    # Provisioning dashboard/datasource Grafana
    - name: grafana-config
      hostPath:
        path: ${PWD}/grafana/provisioning
        type: Directory

    # Configurazione principale Grafana, al container passo solo grafana.ini
    - name: grafana-ini
      hostPath:
        path: ${PWD}/grafana
        type: Directory