apiVersion: v1
kind: Pod
metadata:
  # 'name' è l'identificatore tecnico e univoco del pod all'interno del cluster/container engine.
  # Deve essere unico per ogni pod e viene usato dai comandi di gestione (es: podman, kubectl).
  name: dt-${POD_NAME}

  labels:
    # 'app' è una label generica che permette di raggruppare tutte le risorse che fanno parte della stessa applicazione.
    app: DigitalTwin

    # 'instance' è una label logica che identifica l'istanza funzionale o il ruolo del pod.
    # Può essere usata per filtrare, monitorare o gestire gruppi di pod che rappresentano, ad esempio, diversi palletizer.
    # A differenza di 'name', può essere duplicata su più pod se necessario.
    instance: ${POD_NAME}
spec:
  restartPolicy: Always

  containers:
    
    - name: mosquitto
      image: docker.io/eclipse-mosquitto:latest
      ports:
        - containerPort: 1883
          hostPort: ${HOST_PORT}   # Qui imposto una porta per essere raggiungibile dall'esterno
          protocol: TCP
      volumeMounts:
        - name: mosquitto-conf
          mountPath: /mosquitto/config 

    - name: timescaledb
      image: docker.io/timescale/timescaledb:latest-pg15
      ports:
        - hostPort: 5432
          protocol: TCP
      command:                     # Imposto qui le variabili di ambiente per via di un problema noto con le immagini postgres (sul quale timescaleDB è basato)
          - /bin/bash
          - -c
          - |
            echo "Avvio TimescaleDB con setup automatico..."
            
            export POSTGRES_HOST_AUTH_METHOD=trust        
            export POSTGRES_DB=mqtt_data
            export POSTGRES_USER=mqtt_user
            export POSTGRES_PASSWORD=mqtt_password
            export POSTGRES_INITDB_ARGS="--auth-host=trust --auth-local=trust"
            export TZ=Europe/Rome
            export PGTZ=Europe/Rome
            if [ ! -f /var/lib/postgresql/data/PG_VERSION ]; then
              echo "Database non esistente, inizializzazione automatica..."
            else
              echo "Database esistente trovato, avvio normale"
            fi
            
            echo "Avvio PostgreSQL/TimescaleDB con variabili impostate..."
            exec docker-entrypoint.sh postgres
        
      volumeMounts:
        - name: timescale-data
          mountPath: /var/lib/postgresql/data
        - name: timescale-init
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true

    - name: metabase
      image: docker.io/metabase/metabase:latest
      ports:
      - containerPort: 3000
        hostPort: ${METABASE_PORT} # Porta per l'interfaccia web di Metabase
        protocol: TCP
      environment:
        # Connessione al database TimescaleDB per l'analisi dei dati
        - name: MB_DB_TYPE
          value: "postgres"
        - name: MB_DB_DBNAME
          value: "mqtt_data"
        - name: MB_DB_PORT
          value: "5432"
        - name: MB_DB_USER
          value: "mqtt_user"
        - name: MB_DB_PASS
          value: "mqtt_password"
        - name: MB_DB_HOST
          value: "localhost" # I container nello stesso pod condividono la rete
      volumeMounts:
        - name: metabase-data
          mountPath: /metabase.db # Persistenza del database interno di Metabase

    - name: go-client
      image: docker.io/alpine:latest
      workingDir: /app
      command: ["./mqtt_to_timescale"]
      args: ["${POD_NAME}"]
      environment:
        - name: MQTT_BROKER
          value: "tcp://localhost:1883"
        - name: DB_HOST
          value: "localhost"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "mqtt_data"
        - name: DB_USER
          value: "mqtt_user"
        - name: DB_PASSWORD
          value: "mqtt_password"
        - name: TZ 
          value: "Europe/Rome"
      volumeMounts:
        - name: go-client-binary
          mountPath: /app/mqtt_to_timescale    # punto di montaggio all'interno del container
          subPath: mqtt_to_timescale           # dalla cartella del client monta solo il file
          readOnly: true

  volumes:                   # I volumi vengono dichiarati separatamente, da notare che non viene dichiarata nessuna rete
    # Configurazione Mosquitto
    - name: mosquitto-conf
      hostPath:
        path: ${PWD}/mosquitto
        type: Directory

    # Binario client Go
    - name: go-client-binary
      hostPath:
        path: ${PWD}/go_to_timescale
        type: Directory

    # Dati persistenti TimescaleDB
    - name: timescale-data
      hostPath:
        path: ${PWD}/timescale/data/${POD_NAME}
        type: DirectoryOrCreate  # Crea automaticamente la cartella se non esiste

    # Script di inizializzazione TimescaleDB
    - name: timescale-init
      hostPath:
        path: ${PWD}/timescale/init
        type: Directory

    # Dati persistenti Metabase
    - name: metabase-data
      hostPath:
        path: ${PWD}/metabase/data/${POD_NAME}
        type: DirectoryOrCreate