apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    url: localhost:5432
    database: mqtt_data
    user: mqtt_user
    secureJsonData:
      password: mqtt_password
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    isDefault: true
    access: proxy
    editable: true
